### PR TITLE
complete setup webpack and package.json

### PR DESCRIPTION
**Pull request by quanjingchen**

### CODE REVIEW

**Comment by kevinleaves** [comment]
hi

**Comment by tjspitz** [comment]
Looks good!

**Comment by wooseok0717** [comment]
Great! :)

**Comment by tjspitz** [comment]
## Notes re: this pull request

Our previous comments are **not entirely representative** of our process for reviewing this PR. For this initial PR, we implemented a _team approach_ in which all members reviewed the code, live via Zoom, before approving/merging the PR. A sample of comments & ideas during said code review session are as follows:


- "Do we need to update our `.gitignore` file?"
- "Thank you for getting some starter code in our components, Quanjing!"
- "Perhaps our components dir needs sub-dirs (since each component will have many sub-components)."
    * this was deferred to future discussion
- "Can we add additional dependencies x, y, and z?"
    * "We can add additional dependencies in the future, as needs arise."

**Pull request merged**
